name: Build this project with gradle

on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: openvenues/libpostal
          path: libpostal
      - name: Install libtool
        run: |
          cd libpostal
          ./bootstrap.sh
          mkdir data_dir
          ./configure --datadir=`pwd`/data_dir MODEL=senzing
          sudo make -j4
          sudo make install
          sudo ldconfig
      - uses: actions/checkout@v4
        with:
          path: jpostal
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run tests with Gradle Wrapper
        run: |
          cd jpostal
          ./gradlew assemble check
      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: jpostal.jar
          path: jpostal/build/libs/jpostal-linux-x86-64.jar
