name: Build this project with gradle

on:
  push:

jobs:
  build-gradle-project:
    strategy:
      matrix:
        include:
          - platform: ubuntu-latest
            jarSuffix: 'linux-x86-64'
          - platform: ubuntu-latest-arm64
            jarSuffix: 'linux-aarch64'
          - platform: macos-latest
            jarSuffix: 'macos-x86-64'
          - platform: macos-latest-arm64
            jarSuffix: 'macos-aarch64'
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: openvenues/libpostal
          path: libpostal
      - name: Install libtool
        run: |
          cd libpostal
          ./bootstrap.sh
          mkdir data_dir
          ./configure --datadir=`pwd`/data_dir MODEL=senzing
          sudo make -j4
          sudo make install
          sudo ldconfig
      - uses: actions/checkout@v4
        with:
          path: jpostal
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run tests with Gradle Wrapper
        run: |
          cd jpostal
          ./gradlew assemble check

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true
      - name: Upload jar
        uses: actions/upload-artifact@v4
        with: # todo add version to jar name
          name: jpostal-${{ matrix.jarSuffix }}.jar
          path: jpostal/build/libs/jpostal.jar
