name: Release

on:
  workflow_dispatch:

jobs:
  build-jar:
    uses: wherobots/jpostal/.github/workflows/build-and-test.yml@master
  publish:
    needs: build-jar
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # install and build libpostal
      # This is needed for the linking step of the jpostal build
      - uses: actions/checkout@v4
        with:
          repository: openvenues/libpostal
          path: libpostal
      - name: Install libpostal
        run: |
          cd libpostal
          ./bootstrap.sh
          mkdir data_dir
          ./configure --datadir=`pwd`/data_dir
          sudo make -j4
          sudo make install
          sudo ldconfig
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17 # Java 16+ is required for jpostal
      - name: Checkout jpostal
        uses: actions/checkout@v4
        with:
          path: jpostal
      - name: Get jpostal Version from Gradle
        run: |
          VERSION=$(grep '^version' jpostal/build.gradle | awk -F\' '{print $2}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Download libs
        uses: actions/download-artifact@v4
        with:
          path: ./jpostal/otherResources
      - name: Flatten Native Lib Files
        run: |
          cd jpostal/otherResources
          mv ./jpostal-${{ env.VERSION }}-*/** .
          rm -r jpostal-${{ env.VERSION }}-*
      - name: Build multiplatform jar
        run: |
          cd jpostal
          ./gradlew publish --info
          ./gradlew jreleaserDeploy --info
        env:
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.MAVEN_GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          # For releases
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          JRELEASER_MAVENCENTRAL_PASSWORD,: ${{ secrets.MAVEN_PASSWORD }}
          # For snapshots
          JRELEASER_NEXUS2_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          JRELEASER_NEXUS2_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
